function life(){

    let vidas = 5;
    do{
        console.log("Vidas restantes: "+vidas);
        vidas--;
    }while(vidas>=0);

}
function repedido(){
let nombre;
do{

    nombre = prompt("Escribir"); }

while(nombre != "Jhon");

document.write("<h1>Hola "+nombre+"</h1>");
}

function repetir(){

    let nombre;

    while (nombre != "Jhon") {

        nombre = prompt("Di mi nombre");
    }
    document.write("<h1>Hola "+nombre+"</h1>");
}

function vueltas(){
    
}